-- ============================================================
-- FOUNDER STORE – Database Migration
-- ============================================================

-- 1. EXTENSIONS
create extension if not exists "uuid-ossp";

-- ============================================================
-- 2. TABLES
-- ============================================================

-- Categories
create table if not exists public.categories (
  id          bigint generated by default as identity primary key,
  name        text        not null unique,
  slug        text        not null unique,
  description text,
  image_url   text,
  created_at  timestamptz not null default now()
);

-- Products
create table if not exists public.products (
  id           bigint generated by default as identity primary key,
  name         text        not null,
  slug         text        not null unique,
  description  text,
  price        numeric(12,2) not null default 0,
  image_url    text,
  category_id  bigint      references public.categories(id) on delete set null,
  stock        int         not null default 0,
  featured     boolean     not null default false,
  sizes        text[]      default '{S,M,L,XL,XXL}',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Orders
create table if not exists public.orders (
  id              bigint generated by default as identity primary key,
  order_number    text unique not null default 'ORD-' || to_char(now(), 'YYYYMMDD') || '-' || floor(random()*10000)::text,
  user_id         uuid        references auth.users(id) on delete set null,
  customer_name   text        not null,
  phone           text        not null,
  address         text        not null,
  city            text        not null,
  postal_code     text        not null,
  notes           text,
  subtotal        numeric(12,2) not null default 0,
  shipping_cost   numeric(12,2) not null default 15000,
  total           numeric(12,2) not null default 0,
  payment_method  text        not null default 'QRIS',
  payment_status  text        not null default 'Pending Verification',
  order_status    text        not null default 'Pending',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Order Items
create table if not exists public.order_items (
  id           bigint generated by default as identity primary key,
  order_id     bigint      not null references public.orders(id) on delete cascade,
  product_id   bigint      references public.products(id) on delete set null,
  product_name text        not null,
  price        numeric(12,2) not null,
  quantity     int         not null default 1,
  size         text        not null default 'M',
  subtotal     numeric(12,2) not null,
  created_at   timestamptz not null default now()
);

-- ============================================================
-- 3. INDEXES
-- ============================================================

create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists products_slug_idx        on public.products(slug);
create index if not exists products_featured_idx    on public.products(featured) where featured = true;
create index if not exists orders_user_id_idx       on public.orders(user_id);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

-- ============================================================
-- 4. UPDATED_AT TRIGGER
-- ============================================================

create or replace function public.set_updated_at()
returns trigger language plpgsql as
begin new.updated_at = now(); return new; end;;

create or replace trigger products_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

create or replace trigger orders_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- ============================================================
-- 5. ROW LEVEL SECURITY
-- ============================================================

alter table public.categories  enable row level security;
alter table public.products     enable row level security;
alter table public.orders       enable row level security;
alter table public.order_items  enable row level security;

-- Categories & Products – anyone can read
create policy "categories: public read"
  on public.categories for select to anon, authenticated using (true);

create policy "products: public read"
  on public.products for select to anon, authenticated using (true);

-- Orders – customer only sees their own; anon insert allowed (guest checkout)
create policy "orders: anon insert"
  on public.orders for insert to anon, authenticated with check (true);

create policy "orders: owner read"
  on public.orders for select to authenticated
  using ( (select auth.uid()) = user_id );

create policy "order_items: owner read via order"
  on public.order_items for select to authenticated
  using (
    exists (
      select 1 from public.orders o
      where o.id = order_id
        and o.user_id = (select auth.uid())
    )
  );

create policy "order_items: insert"
  on public.order_items for insert to anon, authenticated with check (true);

-- ============================================================
-- 6. SEED DATA (sample categories)
-- ============================================================

insert into public.categories (name, slug, description) values
  ('T-Shirt',     't-shirt',     'Kaos berkualitas untuk sehari-hari'),
  ('Hoodie',      'hoodie',      'Hoodie nyaman dan stylish'),
  ('Pants',       'pants',       'Celana panjang minimalis'),
  ('Shorts Pants','shorts-pants','Celana pendek kasual'),
  ('Cardigan',    'cardigan',    'Cardigan elegan'),
  ('Polo Shirt',  'polo-shirt',  'Polo shirt klasik')
on conflict (slug) do nothing;

-- ============================================================
-- 7. GRANT DATA API ACCESS
-- ============================================================

grant select on public.categories to anon, authenticated;
grant select on public.products    to anon, authenticated;
grant select, insert on public.orders      to anon, authenticated;
grant select, insert on public.order_items to anon, authenticated;
